# Generated by Django 4.2.26 on 2025-12-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_savedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('festival', 'Festival'), ('concert', 'Concert'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('sports', 'Sports'), ('theater', 'Theater'), ('exhibition', 'Exhibition'), ('charity', 'Charity'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
